# Generated by Django 4.1.7 on 2023-03-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_order_orderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="last_spoken_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cs_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
